apiVersion: v1
kind: Service
metadata:
  name: {{ include "ui.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.global.ui.service.port }}
      name: http-ui
      protocol: TCP
      targetPort: {{ .Values.global.ui.service.port }}
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
