apiVersion: v1
kind: Service
metadata:
  name: {{ include "graphql.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.global.graphql.service.port }}
      name: graphql-http
      protocol: TCP
      targetPort: {{ .Values.global.graphql.service.port }}
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
