apiVersion: v1
kind: Secret
metadata:
  name: postgres-sql
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  database-host: {{ .Values.app.postgres.databaseHost | b64enc | quote }}
  database-port: {{ .Values.app.postgres.databasePort | b64enc | quote }}
  database-user: {{ .Values.app.postgres.databaseUser | b64enc | quote }}
  database-password: {{ .Values.app.postgres.databasePassword | b64enc | quote }}
  database-name: {{ .Values.app.postgres.databaseName | b64enc | quote }}
  database-sslmode: {{ .Values.app.postgres.databaseSslmode | b64enc | quote }}
