deployment:
  replicas: 1
  resources:
    limits:
      cpu: 1
      memory: 256Mi
    requests:
      cpu: 512m
      memory: 128Mi
  image:
    name: victoruzunov/graphql
    tag: project
    pullPolicy: Always
app:
  log:
    level: debug
    format: text