deployment:
  image:
    version: "16.4"
  migrations:
    image: victoruzunov/migrate
    pullPolicy: Always
    tag: project
app:
  postgres:
    databaseHost: "localhost"
    databasePort: "5432"
    databaseUser: "postgres"
    databasePassword: "victor12"
    databaseName: "postgres"
    databaseSslmode: "disable"
    dir: "./migrations"