apiVersion: v1
kind: Secret
metadata:
  name: oauth-app
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  client-id: {{ .Values.app.oauth.clientId | b64enc | quote }}
  client-secret: {{ .Values.app.oauth.clientSecret | b64enc | quote }}
  redirect-url: {{ .Values.app.oauth.redirectUrl | b64enc | quote }}
  scopes: {{ .Values.app.oauth.scopes | b64enc | quote }}
  oauth2-state: {{ .Values.app.oauth.oauth2State | b64enc | quote }}
  jwt-key: {{ .Values.app.oauth.jwtKey | b64enc | quote }}
