apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "rest.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - "*"
  gateways:
    - ingress-gateway-configuration
  http:
    - match:
        - uri:
            prefix: "/login"
      route:
        - destination:
            host: {{ include "rest.fullname" . }}
            port:
              number: {{ .Values.global.rest.service.port }}