name: Go CI Pipeline

on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22.5'

    - name: Install dependencies
      run: |
        cd todoservice
        go mod tidy

    - name: Run tests
      run: |
        cd todoservice
        go test -v ./...
    - name: Build
      run: |
        cd todoservice/cmd/todoapp
        go build -o myapp .

  push-docker:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker for the job
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image for REST service
        run: |
          make push
        working-directory: todoservice

      - name: Build and push Docker image for GraphQL service
        run: |
          make push
        working-directory: graphqlServer

      - name: Build and push Docker image for migrations
        run: |
          make push
        working-directory: migrations

      - name: Build and push Docker image for UI
        run: |
          make push
        working-directory: ui
