name: Go CI Pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

permissions:
  contents: read
  pull-requests: write

jobs:

  lint-format-check-rest:
    uses: ./.github/workflows/reusable_checks.yml
    with:
      path: todoservice

  lint-format-check-graphql:
    uses: ./.github/workflows/reusable_checks.yml
    with:
      path: graphqlServer

  build-rest:
    uses: ./.github/workflows/reusable_build.yml
    with:
      path: todoservice

  build-graphql:
    uses: ./.github/workflows/reusable_build.yml
    with:
      path: graphqlServer

  push-docker:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker for the job
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create .env file for REST service
        run: |
          cd todoservice
          echo "${{ secrets.ENV_REST_CONTENT }}" > .env

      - name: Create .env file for GraphQL service
        run: |
          cd graphqlServer
          echo "${{ secrets.ENV_GRAPHQL_CONTENT }}" > .env

      - name: Build and push Docker image for REST service
        run: |
          make push
        working-directory: todoservice

      - name: Build and push Docker image for GraphQL service
        run: |
          make push
        working-directory: graphqlServer

      - name: Build and push Docker image for migrations
        run: |
          make push
        working-directory: migrations

      - name: Build and push Docker image for UI
        run: |
          make push
        working-directory: ui
