name: Go CI Pipeline

on:
  push:
    branches:
      - '*'

permissions:
  contents: read
  pull-requests: write

jobs:

  markdown-file-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli

      - name: Run markdownlint test
        run: markdownlint ./README.md

  lint-format-check-rest:
    uses: ./.github/workflows/reusable-checks.yml
    with:
      path: todoservice

  lint-format-check-graphql:
    uses: ./.github/workflows/reusable-checks.yml
    with:
      path: graphqlServer

  build-rest:
    needs: lint-format-check-rest
    uses: ./.github/workflows/reusable-build.yml
    with:
      path: todoservice

  build-graphql:
    needs: lint-format-check-graphql
    uses: ./.github/workflows/reusable-build.yml
    with:
      path: graphqlServer

  sonar-cloud-test:
    runs-on: ubuntu-latest
    needs: [ build-rest, build-graphql]
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.qualitygate.wait=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}

  snyk-test:
    runs-on: ubuntu-latest
    needs: [ build-rest, build-graphql ]
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.5'
      - name: Install dependencies
        run: |
          cd todoservice
          go mod tidy
          cd ../graphqlServer
          go mod tidy
      - name: Install Snyk
        run: npm install -g snyk
      - name: Authenticate Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth $SNYK_TOKEN

      - name: Run Snyk to check for vulnerabilities
        run: |
          cd todoservice
          snyk test --file=go.mod --severity-threshold=high
          cd ../graphqlServer
          snyk test --file=go.mod --severity-threshold=high

  trivy-scan-todoservice:
    needs: [snyk-test, sonar-cloud-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create .env file for REST service
        run: |
          cd todoservice
          echo "${{ secrets.ENV_REST_CONTENT }}" > .env
      - name: Build Docker image
        run: |
          cd todoservice
          make build
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'victoruzunov/todoservice:project'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  trivy-scan-graphql:
    needs: [build-rest, build-graphql]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create .env file for GraphQL service
        run: |
          cd graphqlServer
          echo "${{ secrets.ENV_GRAPHQL_CONTENT }}" > .env
      - name: Build Docker image
        run: |
          cd graphqlServer
          make build
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'victoruzunov/graphql:project'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  push-docker-images:
    needs: [trivy-scan-todoservice, trivy-scan-graphql]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker for the job
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create .env file for REST service
        run: |
          cd todoservice
          echo "${{ secrets.ENV_REST_CONTENT }}" > .env

      - name: Create .env file for GraphQL service
        run: |
          cd graphqlServer
          echo "${{ secrets.ENV_GRAPHQL_CONTENT }}" > .env

      - name: Build and push Docker image for REST service
        run: |
          make push
        working-directory: todoservice

      - name: Build and push Docker image for GraphQL service
        run: |
          make push
        working-directory: graphqlServer

      - name: Build and push Docker image for migrations
        run: |
          make push
        working-directory: migrations

      - name: Build and push Docker image for UI
        run: |
          make push
        working-directory: ui

  deploy-to-k3d:
    needs: push-docker-images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install k3d
        run: |
          curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash

      - name: Create k3d Cluster
        run: |
          k3d cluster create my-cluster \
            --port 8080:80@loadbalancer \
            --port 8443:443@loadbalancer \
            --k3s-arg "--disable=traefik@server:*" \
            --k3s-arg '--kube-apiserver-arg=anonymous-auth=true@server:*'

      - name: Install Istioctl
        run: |
          curl -L https://istio.io/downloadIstio | ISTIO_VERSION=1.23.3 sh -
          sudo mv istio-1.23.3/bin/istioctl /usr/local/bin/
          istioctl install --set profile=default -y

      - name: Verify Istio CRDs
        run: |
          kubectl get crds | grep istio
          

      - name: Wait for Istio System
        run: |
          kubectl wait --for=condition=available deployment --all -n istio-system --timeout=300s    

      - name: Create Namespace and Enable Istio Injection
        run: |
          kubectl create namespace todoapp-system
          kubectl label namespace todoapp-system istio-injection=enabled

      - name: Deploy Helm Chart
        run: |
          cd charts/todoapp
          helm install todoapp . \
            --namespace todoapp-system --create-namespace

      - name: Verify Application Deployment
        run: |
          kubectl get pods -n todoapp-system

      - name: Tear Down k3d Cluster
        if: always()
        run: |
          k3d cluster delete my-cluster
  
